# Travis-CI currently does not support language=lua. For an up-to-date list
# of supported languages, see: https://docs.travis-ci.com/user/languages/
language: c

# Build on Ubuntu 14.04 LTS Server Edition 64 bit (Trusty Tahr) which is
# currently on beta (instead of precise which is current default):
dist: trusty

# Build inside docker containers instead of virtual machines. These are
# faster, start quicker and support caching. Downside: sudo is not supported
sudo: false

# We cannot use 'sudo apt-get' to install missing apt-packages, see:
#   - https://docs.travis-ci.com/user/installing-dependencies/
#   - https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages:
    - gfortran

env:
  global:
    - PREFIX=$TRAVIS_BUILD_DIR/install
    - PATH=$PREFIX/bin:$PATH

# Build dependencies:
before_install:
  - env
  - source ./tests/travis/build_common.sh
# Although the archives are included, need some dev files for now:
  - SILENT ./tests/travis/build_luajit.sh
  - SILENT ./tests/travis/build_lpeg.sh
  - SILENT ./tests/travis/build_fftw3.sh
#  - SILENT ./tests/travis/build_lapack.sh
  - SILENT ./tests/travis/build_nfft3.sh
#  - SILENT ./tests/travis/build_nlopt2.sh

# For coverage:
  - SILENT ./tests/travis/build_luarocks.sh
  - SILENT luarocks install luacov
  - SILENT luarocks install luacov-coveralls

# Build MAD:
install:
  - cd src
  - make -f Makefile.linux
  - cd ..

  # Symlink 'mad' in PATH:
  - mkdir -p $PREFIX/bin
  - ln -s $(readlink -f ./src/mad) $PREFIX/bin

# Run tests:
script:
  - cd tests/utests
  - mad all.mad
  # Run coverage on subset:
  - export LUA_PATH=$PREFIX/share/lua/5.1/?.lua
  - mad -lluacov all.mad -p 'Test[^_]' -x LHC

# Submit coverage report, etc:
after_success:
  # Make pathes relative to root directory and submit from there - for best
  # integration with coveralls.io:
  - sed -rn -e "/[0-9]+:\//{s#:$TRAVIS_BUILD_DIR/#:#;p;n;p}" -i luacov.stats.out
  - mv luacov.stats.out ../..
  - cd ../..
  - luacov-coveralls
