# Travis-CI currently does not support language=lua. For an up-to-date list
# of supported languages, see: https://docs.travis-ci.com/user/languages/
language: c

# Build on Ubuntu 14.04 LTS Server Edition 64 bit (Trusty Tahr) which is
# currently on beta (instead of precise which is current default):
dist: trusty

# Build inside docker containers instead of virtual machines. These are
# faster, start quicker and support caching. Downside: sudo is not supported
sudo: false

# We cannot use 'sudo apt-get' to install missing apt-packages, see:
#   - https://docs.travis-ci.com/user/installing-dependencies/
#   - https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages:
    - gfortran

# Build dependencies:
before_install:
  - source .travis/build_common.sh
  - SILENT .travis/build_luajit.sh
  - SILENT .travis/build_lpeg.sh
  - SILENT .travis/build_fftw3.sh
  - SILENT .travis/build_lapack.sh
  - SILENT .travis/build_nfft3.sh
  - SILENT .travis/build_nlopt2.sh

# Build MAD:
install:
  - cd src
  - make -f Makefile.linux
  - cd ..

# Run tests:
script:
  - cd tests/utests
  - ../../src/mad all.mad

# Submit coverage report, etc:
after_success:
  - true
