#! /bin/bash

# This is a fake 'lua' binary.

# It is not equivalent to a symlink:
# - strip MAD banner
# - keep 'mad' as command name

MAD_ROOT=$(readlink -f "$(dirname $BASH_SOURCE)"/..)
$MAD_ROOT/src/mad "$@" | tail -n +7
